fix(API seeds): set SQL sequences to correct values
Previously, when a user tried to create a new order, they received this
error: 'duplicate key value violates unique constraint "orders_pkey"'.
This is because some seed files inserted new rows by manually specifying
their IDs. Because of this, PostgreSQL sequences were out of sync, hence
the error when trying to create new rows without specifying the ID. This
commit adjusts sequences for all tables where IDs were specified
manually in seed files. The following DB tables were affected:

- orders
- addresses
- service_centers
- warranty_requests
- fundraising_campaigns