fix(API): resolve TypeScript 'rootDir' issues
When running "npm run type-check" on the API codebase, TypeScript
compiler returns something like this:

error TS6059: File '/home/lyoshas/onlineStore/server/db-migrations/2023
1025061656_cities.ts' is not under 'rootDir' '/home/lyoshas/onlineStore
/server/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'

This error occurs because the 'rootDir' option in tsconfig.json didn't
include migration and seeding files. This commit fixes this by changing
the 'rootDir' option value from './src' to './'